<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete(); // generated by
            $table->string('name');
            $table->string('type'); // daily_sales, inventory_valuation, stock_movement, purchase_order_summary
            $table->enum('format', ['pdf', 'excel', 'csv'])->default('pdf');
            $table->string('status', 20)->default('pending'); // pending, processing, completed, failed
            $table->text('filters')->nullable(); // JSON of filters applied
            $table->string('file_path')->nullable();
            $table->integer('file_size')->nullable();
            $table->timestamp('generated_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->text('error_message')->nullable();
            $table->timestamps();
            
            $table->index(['user_id', 'created_at']);
            $table->index('type');
            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
